version: '3.3'
services:
  tb4_simulator:
    shm_size: 24G
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - USER_ID=$USER_ID
        - USER_NAME=$USER_NAME
    image: tb4_simulator
    container_name: TurtleBot4Simulator
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./dataset:/home/${USER_NAME}/data
      - ./src:/home/${USER_NAME}/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: ["tail", "-f", "/dev/null"]
    privileged: true
    runtime: nvidia