version: '3.3'
services:
  tb4_navstack_jazzy:
    shm_size: 24G
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - USER_ID=$USER_ID
        - USER_NAME=$USER_NAME
    image: tb4_navstack_jazzy
    container_name: TurtleBot4NavStack_Jazzy
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./dataset:/home/${USER_NAME}/data
      - ./src:/home/${USER_NAME}/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: ["tail", "-f", "/dev/null"]
    privileged: true
